name = "verify"
main = "src/entry-v1.2.js"
compatibility_date = "2026-08-12"
workers_dev = true

[build]
command = "node scripts/write-build-meta.mjs"

[[kv_namespaces]]
binding = "CURATOR_VERIFY_RECORDS"
id = "bf7fb04aa1754f729acd62595bf21004"

[version_metadata]
binding = "CF_VERSION_METADATA"

[observability]
enabled = true
